/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UASProject;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author ANNISA INTAN NURAINI
 */
public class AdminLogin extends javax.swing.JPanel {
    
    private AdminInterface Admin;
    public String username = "Admin";
    public String password = "admin123";
    public int result;
    public int test(){
        return result;
    };
    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }
    
    public void addEvent (AdminInterface event){
        this.Admin = event;
    }
    
    public void ClearTextField(){
        TFusernameAdmin.setText("");
        PFpasswordAdmin.setText("");
        BTloginAdmin.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BTloginAdmin = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        TFusernameAdmin = new javax.swing.JTextField();
        PFpasswordAdmin = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(229, 234, 143));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("CV. KARYA BANGSA");

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel4.setText("Jl. Persada Agung no. 2, Lemah Abang, Cikarang Utara. Kabupaten Bekasi ");

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setText("Hello, Admin!");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel2.setText("Username ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel3.setText("Password");

        BTloginAdmin.setBackground(new java.awt.Color(255, 72, 57));
        BTloginAdmin.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        BTloginAdmin.setText("Login");
        BTloginAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTloginAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTloginAdminMouseClicked(evt);
            }
        });
        BTloginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTloginAdminActionPerformed(evt);
            }
        });

        warningLabel.setBackground(new java.awt.Color(255, 51, 51));
        warningLabel.setText("\n");

        TFusernameAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFusernameAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFusernameAdminActionPerformed(evt);
            }
        });

        PFpasswordAdmin.setBackground(new java.awt.Color(149, 213, 168));
        PFpasswordAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PFpasswordAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addComponent(jLabel5)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BTloginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFusernameAdmin)
                            .addComponent(PFpasswordAdmin))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFusernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PFpasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTloginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTloginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTloginAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTloginAdminActionPerformed

    private void BTloginAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTloginAdminMouseClicked
        // TODO add your handling code here:
        Admin.loginBT_Admin();
        if (TFusernameAdmin.getText().equals(username)&&PFpasswordAdmin.getText().equals(password)){
            result = 1;
        }
        else {
            warningLabel.setText("You got input wrong for password or username. please try again!");
            result = 0;
        }
    }//GEN-LAST:event_BTloginAdminMouseClicked

    private void TFusernameAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFusernameAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFusernameAdminActionPerformed

    private void PFpasswordAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PFpasswordAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PFpasswordAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTloginAdmin;
    private javax.swing.JPasswordField PFpasswordAdmin;
    private javax.swing.JTextField TFusernameAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
