/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UASProject;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ANNISA INTAN NURAINI
 */
public class AdminEditMenu extends javax.swing.JPanel {
    private AdminInterface Admin;
    /**
     * Creates new form AdminEditMenu
     */
    
    Statement st;
    Connection cn;
    
    public AdminEditMenu() {
        initComponents();
        this.cn = connectivity.connected();
    }
    
    public void addEvent(AdminInterface event){
        this.Admin = event;
    }
    
    public void ClearTextFieldEmployeeIDEdit(){
        TFEmployeeIDcheck_EditDataAdmin.setText(" ");
    }
    
    public void ClearTextFieldEmployeeEdit(){
        TFEmployeeName_EditDataAdmin.setText(" ");
        TFEmployeeID_EditDataAdmin.setText(" ");
        TFManagerID_EditDataAdmin.setText(" ");
        TFDOB_EditDataAdmin.setText(" ");
        SBoxPosition_EditDataAdmin.setSelectedIndex(0);
        TFJoinYear_EditDataAdmin.setText(" ");
        TFEmployeeAddress_EditDataAdmin.setText(" ");
        TFEmployeeEmail_EditDataAdmin.setText(" ");
        TFEmployeePhone_EditDataAdmin.setText(" ");
        TFEmployeeIDcheck_DetailSalaryAdmin.setText("");
    }
    
    public void ClearTextFieldEmployeeSalaryEdit(){
        TFEmployeeIDcheck_DetailSalaryAdmin.setText(" ");
        TFMainSalary_DetailSalaryAdmin.setText(" ");
        TFAbsence_DetailSalaryAdmin.setText(" ");
        TFOvertime_DetailSalaryAdmin.setText(" ");
        TFBonus_DetailSalaryAdmin.setText(" ");
        TFSalaryTotal_DetailSalaryAdmin.setText(" ");
        TFStatus_DetailSalaryAdmin.setText(" ");
    }
    int MainSalary;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        TFEmployeeName_EditDataAdmin = new javax.swing.JTextField();
        TFEmployeeID_EditDataAdmin = new javax.swing.JTextField();
        TFManagerID_EditDataAdmin = new javax.swing.JTextField();
        SBoxPosition_EditDataAdmin = new javax.swing.JComboBox<>();
        TFJoinYear_EditDataAdmin = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        TFEmployeeAddress_EditDataAdmin = new javax.swing.JTextField();
        TFEmployeeEmail_EditDataAdmin = new javax.swing.JTextField();
        TFEmployeePhone_EditDataAdmin = new javax.swing.JTextField();
        ButtonSaveChangesEditDataAdmin = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFEmployeeIDcheck_EditDataAdmin = new javax.swing.JTextField();
        ButtonSeeDetailsDataEmployee_EditDataAdmin = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        TFDOB_EditDataAdmin = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        TFMainSalary_DetailSalaryAdmin = new javax.swing.JTextField();
        TFAbsence_DetailSalaryAdmin = new javax.swing.JTextField();
        TFOvertime_DetailSalaryAdmin = new javax.swing.JTextField();
        TFBonus_DetailSalaryAdmin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel77 = new javax.swing.JLabel();
        TFSalaryTotal_DetailSalaryAdmin = new javax.swing.JTextField();
        ButtonSaveChanges_DetailSalaryAdmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFEmployeeIDcheck_DetailSalaryAdmin = new javax.swing.JTextField();
        ButtonSeeDetails_DataSalaryAdmin = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        TFStatus_DetailSalaryAdmin = new javax.swing.JTextField();
        ButtonClearText_DetailSalaryAdmin = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        backEditDataAdmin = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 234, 143));

        jTabbedPane1.setBackground(new java.awt.Color(242, 125, 95));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(995, 650));

        jPanel6.setBackground(new java.awt.Color(206, 210, 224));
        jPanel6.setPreferredSize(new java.awt.Dimension(995, 610));

        jLabel62.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel62.setText("Data Employee");

        jLabel63.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel63.setText("Employee Name ");

        jLabel64.setText("Employee ID ");

        jLabel65.setText("Manager ID");

        jLabel66.setText("Position");

        jLabel67.setText("Join Year");

        jLabel68.setText("Employee address");

        jLabel69.setText("Employee phone");

        jLabel70.setText("Employee email");

        TFEmployeeName_EditDataAdmin.setEditable(false);
        TFEmployeeName_EditDataAdmin.setBackground(new java.awt.Color(242, 210, 149));
        TFEmployeeName_EditDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmployeeName_EditDataAdminActionPerformed(evt);
            }
        });

        TFEmployeeID_EditDataAdmin.setEditable(false);
        TFEmployeeID_EditDataAdmin.setBackground(new java.awt.Color(242, 210, 149));

        TFManagerID_EditDataAdmin.setBackground(new java.awt.Color(242, 125, 95));

        SBoxPosition_EditDataAdmin.setBackground(new java.awt.Color(242, 125, 95));
        SBoxPosition_EditDataAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assistent Resource", "Data Scientist", "Developer Engineering", "External Developer", "Head Division Creative ", "Human Resource and Development", "Internal Developer ", "Java Programmer", "JavaScript Programmer ", "Phyton Programmer", "Android Development", "UI/UX Designer ", "others.." }));
        SBoxPosition_EditDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SBoxPosition_EditDataAdminActionPerformed(evt);
            }
        });

        TFJoinYear_EditDataAdmin.setEditable(false);
        TFJoinYear_EditDataAdmin.setBackground(new java.awt.Color(242, 210, 149));

        jLabel71.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel71.setText("Contact Employee");

        TFEmployeeAddress_EditDataAdmin.setEditable(false);
        TFEmployeeAddress_EditDataAdmin.setBackground(new java.awt.Color(242, 210, 149));

        TFEmployeeEmail_EditDataAdmin.setEditable(false);
        TFEmployeeEmail_EditDataAdmin.setBackground(new java.awt.Color(242, 210, 149));

        TFEmployeePhone_EditDataAdmin.setEditable(false);
        TFEmployeePhone_EditDataAdmin.setBackground(new java.awt.Color(242, 210, 149));

        ButtonSaveChangesEditDataAdmin.setBackground(new java.awt.Color(241, 255, 117));
        ButtonSaveChangesEditDataAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSaveChangesEditDataAdmin.setText("save changes");
        ButtonSaveChangesEditDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveChangesEditDataAdminActionPerformed(evt);
            }
        });

        jLabel78.setText("Date of Birth");

        jLabel1.setText("Enter Employee ID you want to edit!");

        jLabel2.setText("Employee ID");

        TFEmployeeIDcheck_EditDataAdmin.setBackground(new java.awt.Color(242, 125, 95));
        TFEmployeeIDcheck_EditDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmployeeIDcheck_EditDataAdminActionPerformed(evt);
            }
        });

        ButtonSeeDetailsDataEmployee_EditDataAdmin.setBackground(new java.awt.Color(241, 255, 117));
        ButtonSeeDetailsDataEmployee_EditDataAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSeeDetailsDataEmployee_EditDataAdmin.setText("see details");
        ButtonSeeDetailsDataEmployee_EditDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSeeDetailsDataEmployee_EditDataAdminActionPerformed(evt);
            }
        });

        TFDOB_EditDataAdmin.setEditable(false);
        TFDOB_EditDataAdmin.setBackground(new java.awt.Color(242, 210, 149));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSaveChangesEditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(191, 191, 191)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ButtonSeeDetailsDataEmployee_EditDataAdmin)
                                        .addComponent(TFEmployeeIDcheck_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel65, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel78, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TFEmployeeName_EditDataAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                        .addComponent(TFEmployeeID_EditDataAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                        .addComponent(TFManagerID_EditDataAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                        .addComponent(SBoxPosition_EditDataAdmin, 0, 259, Short.MAX_VALUE)
                                        .addComponent(TFJoinYear_EditDataAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                        .addComponent(TFDOB_EditDataAdmin)))))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(361, 361, 361)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TFEmployeeAddress_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TFEmployeeEmail_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TFEmployeePhone_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jSeparator2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFEmployeeIDcheck_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonSeeDetailsDataEmployee_EditDataAdmin)
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel71))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(TFEmployeeName_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(TFEmployeeAddress_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(TFEmployeeID_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel70)
                    .addComponent(TFEmployeeEmail_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(TFManagerID_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69)
                    .addComponent(TFEmployeePhone_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(SBoxPosition_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(TFJoinYear_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(TFDOB_EditDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonSaveChangesEditDataAdmin)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Employee", jPanel6);

        jPanel9.setBackground(new java.awt.Color(206, 210, 224));

        jLabel72.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel72.setText("You can edit employee's salary here!");

        jLabel73.setText("Main salary");

        jLabel74.setText("Absence");

        jLabel75.setText("Overtime");

        jLabel76.setText("Bonus");

        TFMainSalary_DetailSalaryAdmin.setEditable(false);
        TFMainSalary_DetailSalaryAdmin.setBackground(new java.awt.Color(242, 210, 149));

        TFAbsence_DetailSalaryAdmin.setBackground(new java.awt.Color(242, 125, 95));
        TFAbsence_DetailSalaryAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAbsence_DetailSalaryAdminActionPerformed(evt);
            }
        });

        TFOvertime_DetailSalaryAdmin.setBackground(new java.awt.Color(242, 125, 95));

        TFBonus_DetailSalaryAdmin.setEditable(false);
        TFBonus_DetailSalaryAdmin.setBackground(new java.awt.Color(242, 210, 149));

        jLabel77.setText("Salary Total");

        TFSalaryTotal_DetailSalaryAdmin.setEditable(false);
        TFSalaryTotal_DetailSalaryAdmin.setBackground(new java.awt.Color(242, 210, 149));

        ButtonSaveChanges_DetailSalaryAdmin.setBackground(new java.awt.Color(241, 146, 90));
        ButtonSaveChanges_DetailSalaryAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSaveChanges_DetailSalaryAdmin.setText("save changes");
        ButtonSaveChanges_DetailSalaryAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveChanges_DetailSalaryAdminActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Employee ID you want to edit!");

        jLabel4.setText("Employee ID");

        TFEmployeeIDcheck_DetailSalaryAdmin.setBackground(new java.awt.Color(242, 125, 95));

        ButtonSeeDetails_DataSalaryAdmin.setBackground(new java.awt.Color(241, 255, 117));
        ButtonSeeDetails_DataSalaryAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSeeDetails_DataSalaryAdmin.setText("see details");
        ButtonSeeDetails_DataSalaryAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSeeDetails_DataSalaryAdminActionPerformed(evt);
            }
        });

        jLabel5.setText("Status");

        TFStatus_DetailSalaryAdmin.setEditable(false);
        TFStatus_DetailSalaryAdmin.setBackground(new java.awt.Color(242, 210, 149));

        ButtonClearText_DetailSalaryAdmin.setBackground(new java.awt.Color(241, 255, 117));
        ButtonClearText_DetailSalaryAdmin.setText("Clear");
        ButtonClearText_DetailSalaryAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearText_DetailSalaryAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(TFSalaryTotal_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFStatus_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ButtonSeeDetails_DataSalaryAdmin))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(ButtonSaveChanges_DetailSalaryAdmin)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonClearText_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(111, 111, 111)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TFBonus_DetailSalaryAdmin)
                                            .addComponent(TFMainSalary_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TFOvertime_DetailSalaryAdmin)
                                            .addComponent(TFAbsence_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TFEmployeeIDcheck_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 484, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFEmployeeIDcheck_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSeeDetails_DataSalaryAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel72)
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(TFMainSalary_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(TFAbsence_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75)
                    .addComponent(TFOvertime_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(TFBonus_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel77)
                    .addComponent(TFSalaryTotal_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TFStatus_DetailSalaryAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSaveChanges_DetailSalaryAdmin)
                    .addComponent(ButtonClearText_DetailSalaryAdmin))
                .addGap(194, 194, 194))
        );

        jTabbedPane1.addTab("Detail Salary", jPanel9);

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel16.setText("EDIT DATA EMPLOYEE");

        backEditDataAdmin.setBackground(new java.awt.Color(255, 52, 100));
        backEditDataAdmin.setText("Back ->");
        backEditDataAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backEditDataAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backEditDataAdmin)
                .addGap(20, 20, 20))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(backEditDataAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backEditDataAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backEditDataAdminMouseClicked
        // TODO add your handling code here:
        Admin.backEditData_Admin();
    }//GEN-LAST:event_backEditDataAdminMouseClicked

    private void SBoxPosition_EditDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SBoxPosition_EditDataAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SBoxPosition_EditDataAdminActionPerformed

    private void ButtonSeeDetailsDataEmployee_EditDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSeeDetailsDataEmployee_EditDataAdminActionPerformed
        // TODO add your handling code here:
        String EmployeeName="";
        String EmployeeID  ="";
        String ManagerID   ="";
        String Position    ="";
        String DateOfBirth ="";
        String JoinYear    ="";
        
        //fetch data from employeedata table in database
        String SQL1 = "SELECT EmployeeName, EmployeeID, ManagerID, Position, DateOfBirth, JoinYear FROM employeedata WHERE EmployeeID =?";
        try {                   
            try (PreparedStatement pst = cn.prepareStatement(SQL1,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY)) {
                pst.setString(1, TFEmployeeIDcheck_EditDataAdmin.getText());
                try (ResultSet rs = pst.executeQuery()) {
                    if(rs.first()) {
                          EmployeeName = rs.getString(1);
                          EmployeeID   = rs.getString(2);
                          ManagerID    = rs.getString(3);
                          Position     = rs.getString(4);
                          DateOfBirth  = rs.getString(5);
                          JoinYear     = rs.getString(6);
                    }
                    rs.close();
                }
                pst.close();
            }
            
            TFEmployeeName_EditDataAdmin.setText(EmployeeName);
            TFEmployeeID_EditDataAdmin.setText(EmployeeID);
            TFManagerID_EditDataAdmin.setText(ManagerID);
            SBoxPosition_EditDataAdmin.setSelectedItem(Position);
            TFDOB_EditDataAdmin.setText(DateOfBirth);
            TFJoinYear_EditDataAdmin.setText(JoinYear);
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminEditMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String EmployeeAddress ="";
        String EmployeeEmail   ="";
        String EmployeePhone   ="";
        
        //fetch data from employeecontact table in database
        String SQL2 = "SELECT EmployeeAddress, EmployeeEmail, EmployeePhone FROM employeecontact WHERE EmployeeID =?";
        try{
            try (PreparedStatement pst = cn.prepareStatement(SQL2, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY)){
                pst.setString(1, TFEmployeeIDcheck_EditDataAdmin.getText());
                try (ResultSet rs = pst.executeQuery()){
                    if (rs.first()){
                        EmployeeAddress = rs.getString(1);
                        EmployeeEmail   = rs.getString(2);
                        EmployeePhone   = rs.getString(3);
                    }
                    rs.close();
                }
                pst.close();
            }
            TFEmployeeAddress_EditDataAdmin.setText(EmployeeAddress);
            TFEmployeeEmail_EditDataAdmin.setText(EmployeeEmail);
            TFEmployeePhone_EditDataAdmin.setText(EmployeePhone);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminEditMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ClearTextFieldEmployeeIDEdit();
    }//GEN-LAST:event_ButtonSeeDetailsDataEmployee_EditDataAdminActionPerformed

    private void TFEmployeeName_EditDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmployeeName_EditDataAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmployeeName_EditDataAdminActionPerformed

    private void TFEmployeeIDcheck_EditDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmployeeIDcheck_EditDataAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmployeeIDcheck_EditDataAdminActionPerformed

    private void ButtonSaveChangesEditDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveChangesEditDataAdminActionPerformed
        // TODO add your handling code here:
        String ManagerID  = TFManagerID_EditDataAdmin.getText();
        String Position   = SBoxPosition_EditDataAdmin.getSelectedItem().toString();
        String EmployeeID = TFEmployeeID_EditDataAdmin.getText();
        
        //Update data employeedata
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM employeedata;");
            st.executeUpdate("UPDATE employeedata SET ManagerID = '"+ManagerID+"' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeedata SET Position = '"+Position+"' WHERE EmployeeID = '"+EmployeeID+"'");
            rs.close();
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminEditMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Update data employeelogin
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM employeelogin;");
            st.executeUpdate("UPDATE employeelogin SET ManagerID ='"+ManagerID+"' WHERE EmployeeID = '"+EmployeeID+"'");
            rs.close();
            st.close();
        } catch (SQLException ex){
            Logger.getLogger(AdminEditMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Update data employeetable
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM employeetable;");
            st.executeUpdate("UPDATE employeetable SET ManagerID = '"+ManagerID+"' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeetable SET Position = '"+Position+"' WHERE EmployeeID = '"+EmployeeID+"'");
            rs.close();
            st.close();
        } catch (SQLException ex){
            Logger.getLogger(AdminEditMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Update data employeesalary
        int position    = SBoxPosition_EditDataAdmin.getSelectedIndex();
        if (position == 0 || position == 1){
            MainSalary = 8300000;
        }
        else if (position == 2 || position == 3 || position == 6){
            MainSalary = 7200000;
        }
        else if (position == 4 || position == 12){
            MainSalary = 6200000;
        }
        else if (position == 5 || position == 8 || position == 9){
            MainSalary = 9700000;
        }
        else if (position == 7 || position == 10 || position == 11){
            MainSalary = 11800000;
        }
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM employeesalary;");
            st.executeUpdate("UPDATE employeesalary SET MainSalary = '"+MainSalary+"' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeesalary SET Absence = '0' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeesalary SET Overtime = '0' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeesalary SET SalaryTotal = '"+MainSalary+"' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeesalary SET Status = 'Salary not set' WHERE EmployeeID = '"+EmployeeID+"'");
        } catch (SQLException ex) {
            Logger.getLogger(AdminEditMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        ClearTextFieldEmployeeEdit();
    }//GEN-LAST:event_ButtonSaveChangesEditDataAdminActionPerformed

    private void ButtonSeeDetails_DataSalaryAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSeeDetails_DataSalaryAdminActionPerformed
        // TODO add your handling code here:
        int MainSalary    ;
        int Absence       ;
        int Overtime      ;
        int Bonus         ;
        int SalaryTotal   ;
        String Status     = " ";
        String mainsalary = null, absence = null, overtime = null, bonus = null, salarytotal = null;
        
        //fetch data from employeesalary table in database
        String SQL = "SELECT MainSalary, Absence, Overtime, SalaryTotal, Status FROM employeesalary WHERE EmployeeID =?";
        try{
            try (PreparedStatement pst = cn.prepareStatement(SQL, ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY)){
                pst.setString(1, TFEmployeeIDcheck_DetailSalaryAdmin.getText());
                try (ResultSet rs = pst.executeQuery()){
                    if (rs.first()){
                        MainSalary  = rs.getInt(1);
                        Absence     = rs.getInt(2);
                        Overtime    = rs.getInt(3);
                        SalaryTotal = rs.getInt(4);
                        Status      = rs.getString(5);
                        mainsalary  = Integer.toString(MainSalary);
                        Bonus       = (MainSalary)*(Overtime-Absence);
                        bonus       = Integer.toString(Bonus);
                        salarytotal = Integer.toString(MainSalary+Bonus);
                    }
                    rs.close();
                }
                pst.close();
            }
            
            TFMainSalary_DetailSalaryAdmin.setText(mainsalary);
            TFAbsence_DetailSalaryAdmin.setText(absence);
            TFOvertime_DetailSalaryAdmin.setText(overtime);
            TFBonus_DetailSalaryAdmin.setText(bonus);
            TFSalaryTotal_DetailSalaryAdmin.setText(salarytotal);
            TFStatus_DetailSalaryAdmin.setText(Status);
            
        } catch (SQLException ex) {
                Logger.getLogger(AdminEditMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonSeeDetails_DataSalaryAdminActionPerformed

    private void TFAbsence_DetailSalaryAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAbsence_DetailSalaryAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAbsence_DetailSalaryAdminActionPerformed

    private void ButtonSaveChanges_DetailSalaryAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveChanges_DetailSalaryAdminActionPerformed
        // TODO add your handling code here:
        String MainSalary = TFMainSalary_DetailSalaryAdmin.getText();
        String Absence    = TFAbsence_DetailSalaryAdmin.getText();
        String Overtime   = TFOvertime_DetailSalaryAdmin.getText();
        String EmployeeID = TFEmployeeIDcheck_DetailSalaryAdmin.getText();
        String Status     = "Salary on Set";

        int mainsalary    = Integer.parseInt(MainSalary);
        int absence       = Integer.parseInt(Absence);
        int overtime      = Integer.parseInt(Overtime);
        int bonus         = (mainsalary*(overtime-absence));
        int salarytotal   = mainsalary+bonus;

        String Bonus      = Integer.toString(bonus);
        String SalaryTotal= Integer.toString(salarytotal);

        //update data employeesalary
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM employeesalary;");
            st.executeUpdate("UPDATE employeesalary SET MainSalary = '"+MainSalary+"' WHERE EmployeeID ='"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeesalary SET Absence = '"+Absence+"' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeesalary SET Overtime = '"+Overtime+"' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeesalary SET SalaryTotal = '"+salarytotal+"' WHERE EmployeeID = '"+EmployeeID+"'");
            st.executeUpdate("UPDATE employeesalary SET Status = '"+Status+"' WHERE EmployeeID = '"+EmployeeID+"'");

            TFMainSalary_DetailSalaryAdmin.setText(MainSalary);
            TFAbsence_DetailSalaryAdmin.setText(Absence);
            TFOvertime_DetailSalaryAdmin.setText(Overtime);
            TFBonus_DetailSalaryAdmin.setText(Bonus);
            TFSalaryTotal_DetailSalaryAdmin.setText(SalaryTotal);
            TFStatus_DetailSalaryAdmin.setText(Status);
        } catch (SQLException ex) {
            Logger.getLogger(AdminEditMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonSaveChanges_DetailSalaryAdminActionPerformed

    private void ButtonClearText_DetailSalaryAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearText_DetailSalaryAdminActionPerformed
        // TODO add your handling code here:
        ClearTextFieldEmployeeSalaryEdit();
    }//GEN-LAST:event_ButtonClearText_DetailSalaryAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClearText_DetailSalaryAdmin;
    private javax.swing.JButton ButtonSaveChangesEditDataAdmin;
    private javax.swing.JButton ButtonSaveChanges_DetailSalaryAdmin;
    private javax.swing.JButton ButtonSeeDetailsDataEmployee_EditDataAdmin;
    private javax.swing.JButton ButtonSeeDetails_DataSalaryAdmin;
    private javax.swing.JComboBox<String> SBoxPosition_EditDataAdmin;
    private javax.swing.JTextField TFAbsence_DetailSalaryAdmin;
    private javax.swing.JTextField TFBonus_DetailSalaryAdmin;
    private javax.swing.JTextField TFDOB_EditDataAdmin;
    private javax.swing.JTextField TFEmployeeAddress_EditDataAdmin;
    private javax.swing.JTextField TFEmployeeEmail_EditDataAdmin;
    private javax.swing.JTextField TFEmployeeID_EditDataAdmin;
    private javax.swing.JTextField TFEmployeeIDcheck_DetailSalaryAdmin;
    private javax.swing.JTextField TFEmployeeIDcheck_EditDataAdmin;
    private javax.swing.JTextField TFEmployeeName_EditDataAdmin;
    private javax.swing.JTextField TFEmployeePhone_EditDataAdmin;
    private javax.swing.JTextField TFJoinYear_EditDataAdmin;
    private javax.swing.JTextField TFMainSalary_DetailSalaryAdmin;
    private javax.swing.JTextField TFManagerID_EditDataAdmin;
    private javax.swing.JTextField TFOvertime_DetailSalaryAdmin;
    private javax.swing.JTextField TFSalaryTotal_DetailSalaryAdmin;
    private javax.swing.JTextField TFStatus_DetailSalaryAdmin;
    private javax.swing.JButton backEditDataAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
