/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UASProject;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
/**
 *
 * @author ANNISA INTAN NURAINI
 */
public class AdminMakeNewData extends javax.swing.JPanel {
    private AdminInterface Admin;
    /**
     * Creates new form AdminMakeNewData
     */
    Statement st;
    ResultSet rs;
    Connection cn;
    
    public AdminMakeNewData() {
        initComponents();
        this.cn = connectivity.connected();
    }
    
    public void AddEvent(AdminInterface event){
        this.Admin = event;
    }
    
    String month;
    public String month(){
        return month;
    }
    
    int MainSalary;
    
    public void ClearTextField(){
        TFEmployeeName_AddNewAdmin.setText("");
        TFEmployeeID_AddNewAdmin.setText("");
        TFManagerID_AddNewAdmin.setText("");
        PBPosition_AddNewAdmin.setSelectedIndex(0);
        CBChooseDate_AddNewAdmin.setSelectedIndex(0);
        CBChooseMonth_AddNewAdmin.setSelectedIndex(0);
        CBChooseYear_AddNewAdmin.setSelectedIndex(0);
        TFJoinYear_AddNewAdmin.setText("");
        TFMakeNewPassword_AddNewAdmin.setText("");
        TFEmployeeAddress_AddNewAdmin.setText("");
        TFEmployeeEmail_AddNewAdmin.setText("");
        TFEmployeePhone_AddNewAdmin.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        BTBackAddNewEmployee_Admin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFEmployeeName_AddNewAdmin = new javax.swing.JTextField();
        TFEmployeeID_AddNewAdmin = new javax.swing.JTextField();
        TFManagerID_AddNewAdmin = new javax.swing.JTextField();
        PBPosition_AddNewAdmin = new javax.swing.JComboBox<>();
        TFJoinYear_AddNewAdmin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TFEmployeeAddress_AddNewAdmin = new javax.swing.JTextField();
        TFEmployeeEmail_AddNewAdmin = new javax.swing.JTextField();
        TFEmployeePhone_AddNewAdmin = new javax.swing.JTextField();
        BTAdd_AddNewAdmin = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        TFMakeNewPassword_AddNewAdmin = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        CBChooseDate_AddNewAdmin = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CBChooseMonth_AddNewAdmin = new javax.swing.JComboBox<>();
        CBChooseYear_AddNewAdmin = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(229, 234, 143));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel1.setText("ADD NEW EMPLOYEE");

        BTBackAddNewEmployee_Admin.setBackground(new java.awt.Color(255, 52, 100));
        BTBackAddNewEmployee_Admin.setText("Back ->");
        BTBackAddNewEmployee_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTBackAddNewEmployee_AdminMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setText("Data Employee");

        jLabel3.setText("Employee Name");

        jLabel4.setText("Employee ID");

        jLabel5.setText("Manager ID");

        jLabel6.setText("Position");

        jLabel7.setText("Date of Birth");

        jLabel8.setText("Join Year");

        TFEmployeeName_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFEmployeeName_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmployeeName_AddNewAdminActionPerformed(evt);
            }
        });

        TFEmployeeID_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFEmployeeID_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmployeeID_AddNewAdminActionPerformed(evt);
            }
        });

        TFManagerID_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFManagerID_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFManagerID_AddNewAdminActionPerformed(evt);
            }
        });

        PBPosition_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        PBPosition_AddNewAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assistent Resource", "Data Scientist", "Developer Engineering", "External Developer", "Head Division Creative ", "Human Resource and Development", "Internal Developer ", "Java Programmer", "JavaScript Programmer ", "Phyton Programmer", "Android Development", "UI/UX Designer ", "lainnya.." }));
        PBPosition_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBPosition_AddNewAdminActionPerformed(evt);
            }
        });

        TFJoinYear_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFJoinYear_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFJoinYear_AddNewAdminActionPerformed(evt);
            }
        });

        jLabel12.setText("Employee Address");

        jLabel13.setText("Employee Email");

        jLabel14.setText("Employee Phone");

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel15.setText("Contact Employee");

        TFEmployeeAddress_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFEmployeeAddress_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmployeeAddress_AddNewAdminActionPerformed(evt);
            }
        });

        TFEmployeeEmail_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFEmployeeEmail_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmployeeEmail_AddNewAdminActionPerformed(evt);
            }
        });

        TFEmployeePhone_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFEmployeePhone_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmployeePhone_AddNewAdminActionPerformed(evt);
            }
        });

        BTAdd_AddNewAdmin.setBackground(new java.awt.Color(57, 146, 107));
        BTAdd_AddNewAdmin.setText("Add");
        BTAdd_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAdd_AddNewAdminActionPerformed(evt);
            }
        });

        jLabel16.setText("Make password");

        TFMakeNewPassword_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        TFMakeNewPassword_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMakeNewPassword_AddNewAdminActionPerformed(evt);
            }
        });

        jLabel9.setText("DD");

        CBChooseDate_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        CBChooseDate_AddNewAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CBChooseDate_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBChooseDate_AddNewAdminActionPerformed(evt);
            }
        });

        jLabel10.setText("Month");

        jLabel11.setText("Year");

        CBChooseMonth_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        CBChooseMonth_AddNewAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        CBChooseMonth_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBChooseMonth_AddNewAdminActionPerformed(evt);
            }
        });

        CBChooseYear_AddNewAdmin.setBackground(new java.awt.Color(149, 213, 168));
        CBChooseYear_AddNewAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003" }));
        CBChooseYear_AddNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBChooseYear_AddNewAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTBackAddNewEmployee_Admin)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(TFMakeNewPassword_AddNewAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TFEmployeeName_AddNewAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TFEmployeeID_AddNewAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TFManagerID_AddNewAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PBPosition_AddNewAdmin, javax.swing.GroupLayout.Alignment.LEADING, 0, 292, Short.MAX_VALUE)
                                                    .addComponent(TFJoinYear_AddNewAdmin, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(CBChooseDate_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(CBChooseMonth_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(CBChooseYear_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(13, 13, 13))
                                        .addComponent(BTAdd_AddNewAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFEmployeeAddress_AddNewAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(TFEmployeeEmail_AddNewAdmin)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFEmployeePhone_AddNewAdmin)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTBackAddNewEmployee_Admin)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFEmployeeName_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TFEmployeeID_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TFManagerID_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(PBPosition_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(CBChooseDate_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(CBChooseMonth_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBChooseYear_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TFJoinYear_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TFMakeNewPassword_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TFEmployeeAddress_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TFEmployeeEmail_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TFEmployeePhone_AddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTAdd_AddNewAdmin)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PBPosition_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBPosition_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBPosition_AddNewAdminActionPerformed

    private void BTAdd_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAdd_AddNewAdminActionPerformed
        // TODO add your handling code here:
        //getText from TextField
        String EmployeeName = TFEmployeeName_AddNewAdmin.getText();
        String EmployeeID = TFEmployeeID_AddNewAdmin.getText();
        String ManagerID = TFManagerID_AddNewAdmin.getText();
        String Position = PBPosition_AddNewAdmin.getSelectedItem().toString(); //change selected input to string
        String JoinYear = TFJoinYear_AddNewAdmin.getText();
        String MakePassword = TFMakeNewPassword_AddNewAdmin.getText(); //   hide text password
        String EmployeeAddress = TFEmployeeAddress_AddNewAdmin.getText();
        String EmployeeEmail = TFEmployeeEmail_AddNewAdmin.getText();
        String EmployeePhone = TFEmployeePhone_AddNewAdmin.getText();
        
        //Date for code 
        String date = CBChooseDate_AddNewAdmin.getSelectedItem().toString(); //change selected input to string
        String year = CBChooseYear_AddNewAdmin.getSelectedItem().toString(); //change selected input to string
        
        //Adding saved constructor date
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM dob;");
            st.executeUpdate("INSERT INTO dob VALUES ('"
                +EmployeeID+"', '"+year+"-"+month()+"-"+date+"');");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        //Adding button 
            //Add field database employeedata
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM employeedata;");
            st.executeUpdate("INSERT INTO employeedata VALUES ('" 
                +EmployeeName+"', '"+EmployeeID+"', '"
                +ManagerID+"', '"+Position+"', '"+year+"-"+month()+"-"+date+"', '"+JoinYear+"');");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            
            //Add field database employeelogin
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM employeelogin;");
            st.executeUpdate("INSERT INTO employeelogin VALUES ('"
                +EmployeeID+"', '"+ManagerID+"', '"
                +MakePassword+"');");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
            //Add field database employeetable 
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM employeetable;");
            st.executeUpdate("INSERT INTO employeetable (EmployeeID, EmployeeName, ManagerID, Position) VALUES ('"
                +EmployeeID+"', '"+EmployeeName+"', '"
                +ManagerID+"', '"+Position+"');");
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
            
            //Add field database employeecontact
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM employeecontact;");
            st.executeUpdate("INSERT INTO employeecontact VALUES ('"
                +EmployeeID+"', '"+EmployeeAddress+"', '"
                +EmployeeEmail+"', '"+EmployeePhone+"');");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
            //Add field database employeesalary
        int position = PBPosition_AddNewAdmin.getSelectedIndex();
        if (position == 0 || position == 1){
            MainSalary = 8300000;
        }
        else if (position == 2 || position == 3 || position == 6){
            MainSalary = 7200000;
        }
        else if (position == 4 || position == 12){
            MainSalary = 6200000;
        }
        else if (position == 5 || position == 8 || position == 9){
            MainSalary = 9700000;
        }
        else if (position == 7 || position == 10 || position == 11){
            MainSalary = 11800000;
        }
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM employeesalary;");
            st.executeUpdate("INSERT INTO employeesalary VALUES ('"
                +EmployeeID+"', '"+MainSalary+"', 0, 0, '"+MainSalary+"', 'Salary not set')");
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        ClearTextField();
    }//GEN-LAST:event_BTAdd_AddNewAdminActionPerformed

    private void BTBackAddNewEmployee_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTBackAddNewEmployee_AdminMouseClicked
        // TODO add your handling code here:
        Admin.backNewData_Admin();
    }//GEN-LAST:event_BTBackAddNewEmployee_AdminMouseClicked

    private void TFEmployeeName_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmployeeName_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmployeeName_AddNewAdminActionPerformed

    private void TFEmployeeID_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmployeeID_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmployeeID_AddNewAdminActionPerformed

    private void TFManagerID_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFManagerID_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFManagerID_AddNewAdminActionPerformed

    private void TFJoinYear_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFJoinYear_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFJoinYear_AddNewAdminActionPerformed

    private void TFMakeNewPassword_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMakeNewPassword_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMakeNewPassword_AddNewAdminActionPerformed

    private void TFEmployeeAddress_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmployeeAddress_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmployeeAddress_AddNewAdminActionPerformed

    private void TFEmployeeEmail_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmployeeEmail_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmployeeEmail_AddNewAdminActionPerformed

    private void TFEmployeePhone_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmployeePhone_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmployeePhone_AddNewAdminActionPerformed

    private void CBChooseDate_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBChooseDate_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBChooseDate_AddNewAdminActionPerformed

    private void CBChooseYear_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBChooseYear_AddNewAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBChooseYear_AddNewAdminActionPerformed

    private void CBChooseMonth_AddNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBChooseMonth_AddNewAdminActionPerformed
        // TODO add your handling code here:
        //Set String Month in integer
        String monthChoose = CBChooseMonth_AddNewAdmin.getSelectedItem().toString();
        switch(monthChoose){
            case "January": 
                month = "1";
                break;
            case "February":
                month = "2";
                break;
            case "March":
                month = "3";
                break;
            case "April":
                month = "4";
                break;
            case "May": 
                month = "5";
                break;
            case "June":
                month = "6";
                break;
            case "July":
                month = "7";
                break;
            case "August":
                month = "8";
                break;
            case "September":
                month = "9";
                break;
            case "October":
                month = "10";
                break;
            case "November":
                month = "11";
                break;
            case "December":
                month = "12";
                break;
        }
    }//GEN-LAST:event_CBChooseMonth_AddNewAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAdd_AddNewAdmin;
    private javax.swing.JButton BTBackAddNewEmployee_Admin;
    private javax.swing.JComboBox<String> CBChooseDate_AddNewAdmin;
    private javax.swing.JComboBox<String> CBChooseMonth_AddNewAdmin;
    private javax.swing.JComboBox<String> CBChooseYear_AddNewAdmin;
    private javax.swing.JComboBox<String> PBPosition_AddNewAdmin;
    private javax.swing.JTextField TFEmployeeAddress_AddNewAdmin;
    private javax.swing.JTextField TFEmployeeEmail_AddNewAdmin;
    private javax.swing.JTextField TFEmployeeID_AddNewAdmin;
    private javax.swing.JTextField TFEmployeeName_AddNewAdmin;
    private javax.swing.JTextField TFEmployeePhone_AddNewAdmin;
    private javax.swing.JTextField TFJoinYear_AddNewAdmin;
    private javax.swing.JPasswordField TFMakeNewPassword_AddNewAdmin;
    private javax.swing.JTextField TFManagerID_AddNewAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
